/* ****************************************************************************
 * Copyright 2026 51 Degrees Mobile Experts Limited (51degrees.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 * ***************************************************************************/

using System;
using System.IO;
using System.Text;

namespace Owid.Client.Model
{
    /// <summary>
    /// OWID structure which can be used as a node in a tree.
    /// </summary>
    /// <remarks>
    /// An OWID is a claim about who created some data and when, and it is only
    /// worth anything because it is signed. A caller therefore cannot build
    /// one. An instance reaches calling code by one of two routes: parsing
    /// bytes that were already a complete OWID, or asking a
    /// <see cref="Creator"/> to sign one into existence. There is deliberately
    /// no way to assemble a half-made one, because an unsigned OWID is
    /// indistinguishable from a signed one to the code downstream of it, and
    /// the difference only surfaces later when a verification fails somewhere
    /// nobody is watching.
    ///
    /// The state is read-only for the same reason. A parsed OWID's signature
    /// covers its fields as they arrived, so a caller changing a field
    /// afterwards would be holding something whose signature no longer
    /// describes it.
    /// </remarks>
    public class Owid
    {
		/// <summary>
		/// The byte version of the OWID.
		/// </summary>
		public OwidVersion Version { get; internal set; } = OwidVersion.Version3;

		/// <summary>
		/// Domain associated with the creator.
		/// </summary>
		public string Domain { get; internal set; } = string.Empty;

		/// <summary>
		/// The date and time to the nearest minute in UTC of the creation.
		/// </summary>
		public DateTime Date { get; internal set; } = DateTime.UtcNow;

        /// <summary>
        /// Array of bytes that form the payload.
        /// </summary>
        /// <remarks>
        /// A copy, so that writing into the returned array cannot alter an
        /// OWID whose signature was computed over the original bytes.
        /// </remarks>
        public byte[] Payload => (byte[])PayloadInternal.Clone();

        /// <summary>
        /// How many bytes the payload holds, without copying it.
        /// </summary>
        /// <remarks>
        /// <see cref="Payload"/> hands out a copy, so an application applying
        /// a size limit to a large payload would pay for the copy it is about
        /// to reject. This answers the size question on its own.
        /// </remarks>
        public long PayloadLength => PayloadInternal.LongLength;

        /// <summary>
        /// The payload as a string.
        /// </summary>
        public string PayloadAsString =>
            Encoding.ASCII.GetString(PayloadInternal);

		/// <summary>
		/// Signature for this OWID and it's ancestor. Generated by the
		/// <see cref="Creator"/> instance.
		/// </summary>
        /// <remarks>
        /// A copy, for the same reason as <see cref="Payload"/>.
        /// </remarks>
		public byte[] Signature => (byte[])SignatureInternal.Clone();

        /// <summary>
        /// The payload without copying, for use inside this library where the
        /// bytes are only read or are being set by a parser or the creator.
        /// </summary>
        internal byte[] PayloadInternal { get; set; } = Array.Empty<byte>();

        /// <summary>
        /// The signature without copying, for use inside this library.
        /// </summary>
        internal byte[] SignatureInternal { get; set; } = Array.Empty<byte>();

        /// <summary>
        /// Not public. See the note on the class for why an OWID cannot be
        /// assembled by a caller.
        /// </summary>
        internal Owid() { }

        /// <summary>
        /// Builds an instance from fields a parser has already validated.
        /// </summary>
        internal static Owid CreateForParser(
            OwidVersion version,
            string domain,
            DateTime date,
            byte[] payload,
            byte[] signature)
        {
            return new Owid
            {
                Version = version,
                Domain = domain,
                Date = date,
                PayloadInternal = payload,
                SignatureInternal = signature,
            };
        }

        /// <summary>
        /// Reads a complete OWID from its Base64 form.
        /// </summary>
        /// <param name="value">
        /// The encoded OWID, which may be anything at all. This is external
        /// data, so failing to be an OWID is an ordinary outcome rather than
        /// an error.
        /// </param>
        /// <param name="owid">
        /// The OWID when this returns true, otherwise null.
        /// </param>
        /// <param name="status">
        /// <see cref="OwidParseStatus.Parsed"/> when this returns true,
        /// otherwise why the value is not an OWID.
        /// </param>
        /// <returns>
        /// True when the value is a complete, structurally valid OWID. This
        /// says nothing about whether the signature is genuine, which is a
        /// separate question with its own answer.
        /// </returns>
        public static bool TryParse(
            string? value,
            out Owid? owid,
            out OwidParseStatus status)
        {
            owid = null;
            if (string.IsNullOrEmpty(value))
            {
                status = OwidParseStatus.MissingInput;
                return false;
            }

            // Sized from the encoded length rather than guessed, and decoded
            // without throwing, so that a string which is not Base64 costs a
            // failed comparison rather than an exception. The caller does not
            // choose how often that happens; whoever is sending the data does.
            var destination = new byte[((value.Length + 3) / 4) * 3];
            if (Convert.TryFromBase64String(
                    value, destination, out var written) == false)
            {
                status = OwidParseStatus.InvalidBase64;
                return false;
            }

            var buffer = destination;
            if (written != destination.Length)
            {
                buffer = new byte[written];
                Buffer.BlockCopy(destination, 0, buffer, 0, written);
            }

            return TryParse(buffer, out owid, out status);
        }

        /// <summary>
        /// Reads a complete OWID from a buffer holding exactly one.
        /// </summary>
        /// <param name="buffer">
        /// The bytes, which must be one whole OWID and nothing else. Data
        /// after the envelope is rejected, because on this surface there is
        /// nothing else it could belong to. A stream that carries several
        /// envelopes is read with the reader in
        /// <see cref="Extensions"/> instead.
        /// </param>
        /// <param name="owid">
        /// The OWID when this returns true, otherwise null.
        /// </param>
        /// <param name="status">
        /// <see cref="OwidParseStatus.Parsed"/> when this returns true,
        /// otherwise why the bytes are not an OWID.
        /// </param>
        /// <returns>
        /// True when the bytes are a complete, structurally valid OWID.
        /// </returns>
        public static bool TryParse(
            byte[]? buffer,
            out Owid? owid,
            out OwidParseStatus status)
        {
            if (buffer == null)
            {
                owid = null;
                status = OwidParseStatus.MissingInput;
                return false;
            }

            status = OwidReader.TryRead(buffer, out owid);
            if (status != OwidParseStatus.Parsed)
            {
                owid = null;
                return false;
            }
            return true;
        }

        /// <summary>
        /// Reads one OWID from a stream that may carry more after it.
        /// </summary>
        /// <param name="stream">
        /// The source, read forward only. Its length is never asked for, so a
        /// stream that cannot answer that still works.
        /// </param>
        /// <param name="owid">
        /// The OWID when this returns true, otherwise null.
        /// </param>
        /// <param name="status">
        /// <see cref="OwidParseStatus.Parsed"/> when this returns true,
        /// otherwise why the bytes are not an OWID.
        /// <see cref="OwidParseStatus.MissingInput"/> means the stream had
        /// nothing left, which is how a caller reading a sequence finds out it
        /// has reached the end.
        /// </param>
        /// <returns>
        /// True when one complete OWID was read. Bytes after it are left where
        /// they are, because in a stream they may be the next envelope rather
        /// than rubbish, which is the one way this differs from
        /// <see cref="TryParse(byte[], out Owid, out OwidParseStatus)"/>.
        /// </returns>
        /// <remarks>
        /// Nothing is consumed when an envelope is refused beyond what had
        /// already been read to discover the fault, so a caller that hits a
        /// bad envelope should stop rather than expect the position to be
        /// usable.
        /// </remarks>
        public static bool TryRead(
            Stream? stream,
            out Owid? owid,
            out OwidParseStatus status)
        {
            status = OwidStreamReader.TryRead(stream!, out owid);
            if (status != OwidParseStatus.Parsed)
            {
                owid = null;
                return false;
            }
            return true;
        }

		/// <inheritdoc/>
        public override string ToString()
        {
            return this.AsBase64();
        }
    }
}
