<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Owid.Client.Controllers</AssemblyName>
    <Platforms>AnyCPU</Platforms>
    <DocumentationFile>Owid.Client.Controllers.xml</DocumentationFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <!-- NuGet package properties -->
    <PackageId>Owid.Client.Controllers</PackageId>
    <Title>OWID Client Controllers - ASP.NET Core controllers for OWID</Title>
    <PackageDescription>Open Web Id (OWID) - ASP.NET Core controllers for serving OWID public keys and related endpoints. This package provides ready-to-use controllers for OWID integration.</PackageDescription>
    <PackageIconUrl>https://github.com/SWAN-community/owid/raw/main/images/owl.128.pxls.100.dpi.png</PackageIconUrl>
    <PackageIcon>owl-logo.png</PackageIcon>
    <Description>Open Web Id (OWID) - ASP.NET Core controllers for serving OWID public keys and related endpoints. This package provides ready-to-use controllers for OWID integration.</Description>
    <RepositoryType>git</RepositoryType>
    <NeutralLanguage>en</NeutralLanguage>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Owid.Client\Owid.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\Images\owl-logo.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
