name: Nightly Publish Main

on:
  workflow_dispatch:
    inputs:
      dryrun:
        required: false
        type: boolean
        default: false
  workflow_call:

jobs:
  # Run the common workflow to test and publish the main branch
  Nightly_Publish_Main:
    uses: 51Degrees/common-ci/.github/workflows/nightly-publish-main.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
      build-platform: windows-latest
    secrets: 
      token: ${{ secrets.ACCESS_TOKEN }}
      CodeSigningKeyVaultUrl: ${{ secrets.CODE_SIGNING_KEY_VAULT_URL }}
      CodeSigningKeyVaultClientId: ${{ secrets.CODE_SIGNING_KEY_VAULT_CLIENT_ID }}
      CodeSigningKeyVaultTenantId: ${{ secrets.CODE_SIGNING_KEY_VAULT_TENANT_ID }}
      CodeSigningKeyVaultClientSecret: ${{ secrets.CODE_SIGNING_KEY_VAULT_CLIENT_SECRET }}
      CodeSigningKeyVaultCertificateName: ${{ secrets.CODE_SIGNING_KEY_VAULT_CERTIFICATE_NAME }}
